"use strict";
const CampaignWorld=(()=>{
 const VERSION=1,GENERATOR='continuous-world-1',KEY='campaign-atlas:world:v1:',ACTIVE=KEY+'active';
 const copy=x=>JSON.parse(JSON.stringify(x));
 function hash(text){let n=2166136261;for(const c of text)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0;}
 function create(operation,seed,spatial){if(!/^[a-f0-9]{32}$/.test(seed))throw Error('A 128-bit campaign seed is required.');const nodes=Object.fromEntries(Object.entries(spatial.nodes).map(([id,n])=>[id,{...n,id,position:[n.x*40,n.y*40],provenance:'Authored placement, not a historical deployment'}]));return {version:VERSION,id:operation.id,title:'Ardennes campaign',mapSeed:seed,generator:GENERATOR,crs:'EPSG:3035',atlasOrigin:[-320,150],bounds:[0,0,40000,16800],nodes,routes:Object.fromEntries(Object.entries(spatial.routes).map(([id,points])=>[id,{id:'road-'+id,points:points.map(p=>p.map(x=>x*40)),provenance:'Authored campaign road'}])),river:{id:'river-main',points:[[22400,0],[23800,4200],[23000,6500],[25100,10000],[25400,16800]]},operation:copy(operation),missions:{},forces:{},terrainEvents:[],revision:0};}
 function validate(w,M){if(!w||w.version!==VERSION||w.generator!==GENERATOR||!Array.isArray(w.bounds)||!/^[a-f0-9]{32}$/.test(w.mapSeed))throw Error('Unsupported campaign world.');if(w.crs!=='EPSG:3035'||!Array.isArray(w.atlasOrigin)||!w.atlasOrigin.every(Number.isFinite)||!Number.isInteger(w.revision)||w.revision<0||!w.nodes||!w.routes||!w.missions||!w.forces||!Array.isArray(w.terrainEvents))throw Error('Invalid campaign spatial state.');if(w.id!==w.operation.id)throw Error('Campaign/command identity mismatch.');const x=copy(w);x.operation=M.restore(w.operation);for(const [id,m]of Object.entries(x.missions)){if(m.seed!==x.mapSeed||m.generator!==x.generator||m.commandId!==id||!m.units.every(uid=>x.forces[uid]?.missionId===id))throw Error('Invalid campaign mission binding.');}return x;}
 function terrain(w,x,y,time=Infinity){const i=Math.floor(x/1000),j=Math.floor(y/1000);let woods=false;for(let a=i-1;a<=i+1;a++)for(let b=j-1;b<=j+1;b++){const h=hash(w.mapSeed+'|'+w.generator+'|'+a+'|'+b);const cx=a*1000+(h%800),cy=b*1000+((h>>>10)%800),r=250+(h%450);if(h%3===0&&Math.hypot(x-cx,y-cy)<r)woods=true;}const events=w.terrainEvents.filter(e=>e.at<=time&&e.area&&Math.hypot(x-e.area.x,y-e.area.y)<=e.area.radius);return events.at(-1)?.terrain||(woods?'woods':'open');}
 function cells(w,bounds,size,time){const out=[],r=size/Math.sqrt(3),dy=r*1.5;for(let row=Math.floor(bounds[1]/dy)-1;row<=Math.ceil((bounds[1]+bounds[3])/dy)+1;row++)for(let col=Math.floor(bounds[0]/size)-1;col<=Math.ceil((bounds[0]+bounds[2])/size)+1;col++){const x=(col+(row%2?0.5:0))*size,y=row*dy;if(x<bounds[0]||y<bounds[1]||x>bounds[0]+bounds[2]||y>bounds[1]+bounds[3])continue;out.push({id:size+':'+col+':'+row,x,y,r,terrain:terrain(w,x,y,time)});}return out;}
 function bindMission(w,id,source,M){const out=copy(w),m=out.operation.missions[id];if(!m?.choice)throw Error('Commit a mission first.');if(out.missions[id])return out;const variant=M.variant(out.operation,id,source),n=out.nodes[id];const footprint=[n.position[0]-4000,n.position[1]-2200,8000,6000];out.missions[id]={id:out.id+':'+id,commandId:id,title:variant.situation.title,startTime:m.committedAt,footprint,seed:out.mapSeed,generator:out.generator,sourceHash:out.operation.sourceHashes[id],sourceNumber:source.situation.number,objectives:copy(source.victory),adaptation:'Campaign terrain replaces printed boards and setup zones. West/east deployment halves are authored; printed board-specific victory conditions and special rules require adaptation before combat.',units:variant.instances.map(i=>i.id.startsWith('reserve-r1')?out.id+':'+i.id:out.id+':'+id+':'+i.id),placements:{},placementHistory:[],ready:false};for(const i of variant.instances){const type=variant.counters.find(c=>c.id===i.counterTypeId),uid=i.id.startsWith('reserve-r1')?out.id+':'+i.id:out.id+':'+id+':'+i.id;out.forces[uid]={id:uid,sourceInstance:i.id,type:copy(type),missionId:id,side:type.side,position:null};}return out;}
 function place(w,id,uid,cellId,time){const out=copy(w),m=out.missions[id],unit=out.forces[uid];if(!m||!m.units.includes(uid)||unit?.missionId!==id)throw Error('Unit is not assigned to this mission.');if(m.ready)throw Error('Deployment is locked.');if(time!==out.operation.time)throw Error('Placement requires current campaign time.');const cell=cells(out,m.footprint,250,time).find(c=>c.id===cellId);if(!cell)throw Error('Cell is outside this mission footprint.');const mid=m.footprint[0]+m.footprint[2]/2;if((unit.side==='Allied'&&cell.x>=mid)||(unit.side==='German'&&cell.x<mid))throw Error('Use the highlighted deployment half for this side.');if(Object.entries(m.placements).some(([k,p])=>k!==uid&&p.cellId===cellId))throw Error('This prototype allows one formation counter per hex.');const placement={cellId,position:[cell.x,cell.y],at:time};m.placements[uid]=placement;(m.placementHistory??=[]).push({unitId:uid,...placement});unit.position=placement.position;return out;}
 function placementsAt(m,time){return m.placementHistory?.length?Object.fromEntries(m.placementHistory.filter(p=>p.at<=time).map(p=>[p.unitId,p])):Object.fromEntries(Object.entries(m.placements).filter(([,p])=>p.at<=time));}
 function event(w,e){const out=copy(w);if(out.terrainEvents.some(x=>x.id===e.id))throw Error('Duplicate terrain event.');if(e.at<out.operation.time)throw Error('Terrain changes cannot be backdated.');out.terrainEvents.push(copy(e));return out;}
 const atlasPoint=(w,p)=>[w.atlasOrigin[0]+p[0]/1000,w.atlasOrigin[1]+p[1]/1000];
 function repository(storage,M,spatial){let current=null;const seed=()=>Array.from(crypto.getRandomValues(new Uint8Array(16))).map(x=>x.toString(16).padStart(2,'0')).join('');
 const write=w=>{storage.setItem(KEY+w.id,JSON.stringify(w));storage.setItem(ACTIVE,w.id);current=w;return w;};
 function migrate(raw){const op=M.restore(raw);const existing=storage.getItem(KEY+op.id);return existing?validate(JSON.parse(existing),M):create(op,seed(),spatial);}
 return {load(){const id=storage.getItem(ACTIVE);if(id){current=validate(JSON.parse(storage.getItem(KEY+id)),M);return current;}const old=storage.getItem(M.KEY);return old?write(migrate(old)):null;},get(){return current;},saveOperation(op){let w=current?.id===op.id?copy(current):create(op,seed(),spatial);if(current?.id===op.id){const live=JSON.parse(storage.getItem(KEY+op.id));if(live.revision!==current.revision)throw Error('Campaign changed in another tab. Reload before editing.');}w.operation=copy(op);w.revision++;return write(w);},save(w){const live=JSON.parse(storage.getItem(KEY+w.id));if(live.revision!==w.revision)throw Error('Campaign changed in another tab.');w=copy(w);w.revision++;return write(w);},archive(){if(current){storage.setItem(KEY+'archive:'+current.id,JSON.stringify(current));}},list(){const rows=Object.keys(storage).filter(k=>k.startsWith(KEY)&&!k.includes('archive:')&&k!==ACTIVE).map(key=>{try{const w=validate(JSON.parse(storage.getItem(key)),M);return{key,label:w.title+' | '+M.clock(w.operation.time)+' | '+w.id.slice(0,8)};}catch{return null;}}).filter(Boolean);for(const key of Object.keys(storage).filter(k=>k.startsWith(M.KEY+':archive:'))){const op=M.restore(storage.getItem(key));if(!rows.some(r=>r.key===KEY+op.id))rows.push({key,label:'Import saved operation | '+M.clock(op.time)+' | '+op.id.slice(0,8)});}return rows;},open(key){const raw=JSON.parse(storage.getItem(key));const w=key.startsWith(M.KEY)?migrate(raw):validate(raw,M);return write(w);}};}
 return{VERSION,GENERATOR,KEY,ACTIVE,atlasPoint,placementsAt,hash,create,validate,terrain,cells,bindMission,place,event,repository};
})();
if(typeof module!=='undefined')module.exports=CampaignWorld;
