const fs=require("node:fs"),vm=require("node:vm"),assert=require("node:assert/strict"),path=require("node:path");
const read=f=>fs.readFileSync(path.join(__dirname,f),"utf8");
const ctx=vm.createContext({window:{}});for(const f of ["panzer-situation-data.js","panzer-situation-state.js"])vm.runInContext(read(f),ctx);
const model=vm.runInContext("PanzerSituationModel",ctx),packages=ctx.window.PANZER_SITUATION_LIBRARY;
assert.equal(packages.length,17);
const expected={5:[68,54,25,3],6:[44,19,17,1],7:[41,23,17,2],12:[41,51,26,3],9:[36,37,19,2],10:[16,31,15,1],11:[65,53,27,3],4:[42,34,21,2],8:[30,15,10,2],14:[24,46,18,2],16:[27,24,13,1],13:[88,90,39,2],15:[46,70,26,2],17:[80,72,39,3],18:[63,56,32,3],19:[113,79,39,3],20:[14,11,14,1]};
const fill=(s,d,side)=>{for(const i of model.ground(d).filter(i=>d.counters.find(c=>c.id===i.counterTypeId).side===side)){if(d.deployment?.loads.some(l=>l.passengerId===i.id))continue;const ref=d.deployment?.allowedHexes[i.id].find(r=>model.allowed(d,i.id,r.boardId,r.hexId,s)),b=d.boards.find(b=>b.id===(ref?.boardId||d.setupBoards[side])),h=ref?b.hexes.find(h=>h.id===ref.hexId):b.hexes.find(h=>h.setupAllowed);model.place(s,d,i.id,b.id,h.imageCenter.u,h.imageCenter.v);}};
for(const d of packages){
 const n=d.situation.number,exp=expected[n];assert.deepEqual([d.totals.Allied,d.totals.German,d.counters.length,d.boards.length],exp);
 const base=d.assetBase||"assets/panzer-leader-04/";for(const c of d.counters)assert.ok(fs.existsSync(path.join(__dirname,base,c.artwork)),c.id);
 for(const b of d.boards){assert.equal(b.hexes.length,346);assert.ok(fs.existsSync(path.join(__dirname,base,b.image)));}
 const s=model.create(d);assert.equal(s.stage,d.setupOrder[0]);assert.throws(()=>model.launch(s,d),/Complete/);
 if(d.deployment){const i=d.instances.find(i=>d.counters.find(c=>c.id===i.counterTypeId).side===s.stage&&!d.deployment.loads.some(l=>l.passengerId===i.id)),b=d.boards.find(b=>b.id===d.setupBoards[s.stage]),bad=b.hexes.find(h=>h.setupAllowed&&!model.allowed(d,i.id,b.id,h.id));if(bad)assert.throws(()=>model.place(s,d,i.id,b.id,bad.imageCenter.u,bad.imageCenter.v),/setup zone/);}
 for(const side of d.setupOrder){fill(s,d,side);model.next(s,d);}model.launch(s,d);model.validate(JSON.parse(JSON.stringify(s)),d);assert.equal(Object.keys(s.placements).length,model.ground(d).length);
 const ids=["Allied","German"].map(side=>d.instances.find(i=>d.counters.find(c=>c.id===i.counterTypeId).side===side).id);
 const e=model.draft(s,d,ids,"Hold objective");assert.equal(e.date,d.situation.printedDate);assert.ok(e.scenarioCard.title.startsWith(d.situation.title));assert.equal(e.scenarioCard.date.month,Number(d.situation.printedDate.slice(5,7)));assert.equal(e.executable,false);
 if(n===5){const air=d.instances.filter(i=>i.counterTypeId==='uk-typhoon-rockets');assert.equal(air.length,8);assert.equal(d.airSupport.maxConcurrentAircraft,5);assert.ok(air.every(i=>d.deployment.allowedHexes[i.id].length===0));assert.equal(model.ground(d).length,114);for(const id of ['uk-sexton','uk-achilles','uk-cromwell-goodwood','uk-sherman','uk-bren'])assert.ok(d.deployment.allowedHexes[id+'-01'].every(r=>r.boardId==='A'));assert.ok(d.deployment.allowedHexes['de-rifle-01'].filter(r=>r.boardId==='A').every(r=>!d.boards.find(b=>b.id==='A').hexes.find(h=>h.id===r.hexId).placeIds.includes('grancelles-all')));const b=d.boards.find(b=>b.id==='B');assert.equal(new Set(b.hexes.map(h=>h.id)).size,346);assert.ok(b.hexes.some(h=>h.terrain.base==='water'));assert.ok(b.hexes.filter(h=>h.terrain.base==='water').every(h=>!h.setupAllowed));assert.equal(d.mapModel.places.filter(p=>p.hexes[0].boardId==='B').length,4);assert.equal(d.counters.find(c=>c.id==='uk-cromwell-goodwood').factors.movement,7);assert.equal(d.counters.find(c=>c.id==='de-maultier-goodwood').factors.defense,4);}
 if(n===6||n===7){const b=d.boards.find(b=>b.id==='D');for(const i of d.instances)assert.ok(d.deployment.allowedHexes[i.id].every(r=>r.boardId==='D'&&(i.id.startsWith('de-')?b.hexes.find(h=>h.id===r.hexId).r>7:b.hexes.find(h=>h.id===r.hexId).r<(n===6?8:7))));if(n===6){assert.equal(d.counters.filter(c=>c.nationality==='ca').reduce((n,c)=>n+c.quantity,0),44);assert.ok(d.admission.blockers.some(s=>s.includes('unverified')));assert.ok(d.deployment.allowedHexes['de-block-reichswald-01'].length>1);assert.throws(()=>model.draft(s,d,['ca-rifle-01','de-block-reichswald-01'],'Hold'),/participating counters/);}}
 if(n===12){assert.equal(d.firstSide,'German');assert.equal(d.setupOrder[0],'Allied');assert.deepEqual(Array.from(d.boards,b=>b.id),['A','D','C']);assert.deepEqual(Array.from(d.mapModel.zones.find(z=>z.id==='saar-west-exits').hexes,r=>r.hexId),['P-1','Q-1','R-1','S-1']);}
 if(n===9){assert.equal(d.counters.find(c=>c.id==='uk-tank-bridge').kind,'bridge-equipment');assert.equal(d.counters.find(c=>c.id==='uk-tank-bridge').factors,null);assert.throws(()=>model.draft(s,d,['uk-tank-bridge-01','de-rifle-01'],'Cross'),/participating counters/);}
 if(n===10){const fresh=model.create(d),b=d.boards[0],town=b.hexes.find(h=>h.placeIds.includes('grancelles-all')&&h.setupAllowed);fill(fresh,d,'Allied');model.next(fresh,d);const target=fresh.placements['uk-rifle-01'],th=b.hexes.find(h=>h.id===target.hexId);assert.equal(model.allowed(d,'de-rifle-01','A',th.id,fresh),false);assert.throws(()=>model.place(fresh,d,'de-rifle-01','A',th.imageCenter.u,th.imageCenter.v),/setup zone/);const distance=h=>Math.max(Math.abs(h.q-th.q),Math.abs(h.r-th.r),Math.abs(h.q+h.r-th.q-th.r));const edge=b.hexes.find(h=>h.setupAllowed&&distance(h)===3);assert.ok(model.allowed(d,'de-rifle-01','A',edge.id,fresh));model.place(fresh,d,'de-rifle-01','A',edge.imageCenter.u,edge.imageCenter.v);const invalid=JSON.parse(JSON.stringify(fresh));invalid.placements['de-rifle-01']={...target};assert.throws(()=>model.validate(invalid,d),/Invalid setup/);}
 if(n===11){assert.equal(d.counters.filter(c=>c.nationality==='am').reduce((n,c)=>n+c.quantity,0),35);for(const i of d.instances.filter(i=>/^(us|be)-/.test(i.id)))assert.ok(d.deployment.allowedHexes[i.id].every(r=>r.boardId===(i.id.startsWith('be-')?'A':'D')));assert.equal(d.counters.find(c=>c.id==='de-pziv-w').factors.attack,11);}
 if(n===14){assert.equal(model.create(d).stage,"Allied");assert.notDeepEqual(d.deployment.allowedHexes["us-engineer-01"],d.deployment.allowedHexes["us-engineer-04"]);}
 if(n===16){for(const l of d.deployment.loads)assert.deepEqual(s.placements[l.passengerId],s.placements[l.carrierId]);const bad=JSON.parse(JSON.stringify(s));delete bad.placements["us-81mm-01"];assert.throws(()=>model.validate(bad,d));assert.ok(d.deployment.allowedHexes["de-rifle-01"].every(ref=>d.boards[0].hexes.find(h=>h.id===ref.hexId).r>=28));}
 if(n===13){assert.equal(new Set(d.deployment.allowedHexes['us-rifle-01'].map(r=>r.boardId)).size,2);assert.ok(d.deployment.allowedHexes['de-rifle-01'].every(r=>r.boardId==='C'));assert.ok(d.deployment.allowedHexes['de-rifle-10'].every(r=>r.boardId==='D'));const b=d.boards.find(b=>b.id==='D'),ref=d.deployment.allowedHexes['us-rifle-01'].find(r=>r.boardId==='D'),h=b.hexes.find(h=>h.id===ref.hexId),fresh=model.create(d);model.place(fresh,d,'us-rifle-01','D',h.imageCenter.u,h.imageCenter.v);model.validate(fresh,d);}
 if(n===15){assert.ok(d.illustration.joinedLayout.every(x=>x.clockwiseDegrees===180));assert.equal(d.counters.find(c=>c.id==='us-block').factors,null);const b=d.boards.find(b=>b.id==='D');for(const i of d.instances.filter(i=>i.id.startsWith('de-')))assert.ok(d.deployment.allowedHexes[i.id].every(r=>i.setupGroup==='A'?b.hexes.find(h=>h.id===r.hexId).r<16:b.hexes.find(h=>h.id===r.hexId).r>16));assert.throws(()=>model.draft(s,d,['us-block-01','de-rifle-01'],'Hold'),/participating counters/);}
 if(n===17){assert.equal(d.counters.filter(c=>c.nationality==='uk').reduce((n,c)=>n+c.quantity,0),22);assert.equal(d.counters.find(c=>c.id==='de-panther-w').factors.attack,13);for(const i of d.instances.filter(i=>/^(us|uk)-/.test(i.id)))assert.ok(d.deployment.allowedHexes[i.id].every(r=>r.boardId===(i.setupGroup==='US'?'A':'D')));assert.notDeepEqual(d.deployment.allowedHexes['de-wespe-01'],d.deployment.allowedHexes['de-wespe-02']);}
 if(n===18||n===19){const air=d.instances.filter(i=>d.counters.find(c=>c.id===i.counterTypeId).kind==='aircraft');assert.equal(air.length,n===18?11:6);assert.ok(air.every(i=>d.deployment.allowedHexes[i.id].length===0&&i.availability.turn===(n===18?4:1)));const fresh=model.create(d);fresh.stage='Allied';const b=d.boards.find(b=>b.id===d.setupBoards.Allied),h=b.hexes.find(h=>h.setupAllowed);assert.throws(()=>model.place(fresh,d,air[0].id,b.id,h.imageCenter.u,h.imageCenter.v));assert.ok(!s.placements[air[0].id]);if(n===18){assert.equal(d.airSupport.maxConcurrentFighterFlights,1);assert.deepEqual(Array.from(d.airSupport.groups.filter(g=>g.role==='fighter-bomber'),g=>g.instanceIds.length),[5,5]);}else assert.equal(d.situation.printedEndDate,'1945-01-01');}
 if(n===20){assert.deepEqual(JSON.parse(JSON.stringify(d.deployment.allowedHexes['de-block-01'])),[{boardId:'D',hexId:'BB-6'}]);assert.equal(d.counters.find(c=>c.id==='de-block').factors,null);assert.equal(d.campaignAssignment.number,1);assert.equal(d.parentCampaign.id,'rhine-march-1945');}
 console.log("Package",n,"roster, assets, setup zones, launch, save and dated draft passed.");
}
class E{constructor(tag){this.tag=tag;this.children=[];this.style={};this.attrs={};this.classList={add(){}};}addEventListener(n,f){this["on"+n]=f;}append(...x){this.children.push(...x);}prepend(...x){this.children.unshift(...x);}setAttribute(k,v){this.attrs[k]=v;}replaceChildren(){this.children=[];}showModal(){this.open=true;}close(){this.open=false;}}
const nodes={},body=new E("body"),store=new Map();ctx.document={body,createElement:t=>new E(t),createElementNS:(_,t)=>new E(t),getElementById:id=>nodes[id]||(nodes[id]=new E("section"))};ctx.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};
for(const f of ["panzer-map-art.js","counter-palette-defaults.js","terrain-palette-defaults.js","campaign-appearance.js","panzer-situation-view.js"])vm.runInContext(read(f),ctx);
for(const r of [0,90,180,270]){const p=vm.runInContext(`PanzerMapArt.project(${r},.23,.71)`,ctx),u=vm.runInContext(`PanzerMapArt.unproject(${r},${p.x},${p.y})`,ctx);assert.ok(Math.abs(u.u-.23)<1e-12&&Math.abs(u.v-.71)<1e-12);}
const all=e=>[e,...e.children.flatMap(all)],flow=ctx.window.CampaignSituationWorkflow;
for(const d of packages.filter(d=>d.situation.number!==4)){
 const saved=model.create(d);for(const side of d.setupOrder){fill(saved,d,side);model.next(saved,d);}store.set("campaign-atlas:"+d.id+":v2",JSON.stringify(saved));
 flow.selectPackage(d.id);assert.equal(flow.selectedPackage(),d.id);flow.choose();flow.openMap();
 const dialog=body.children[0];assert.equal(dialog.open,true);assert.equal(all(dialog).filter(e=>e.attrs.class==="panzer-joined-svg").length,d.boards.length);assert.equal(all(dialog).filter(e=>e.attrs.class==="panzer-north-rose").length,1);
 assert.ok(all(dialog).some(e=>e.textContent===d.situation.title+" | Campaign Map Setup"));assert.equal(all(dialog).filter(e=>e.className==="panzer-token").length,model.ground(d).length);
 if(d.situation.number===15)assert.ok(all(dialog).filter(e=>e.attrs.class==='panzer-joined-svg').every(e=>e.attrs.viewBox==='0 0 1130 3138'));
 if(d.situation.number===6)assert.ok(all(dialog).some(e=>e.attrs["data-nationality"]==="ca"));
 if(d.situation.number===5)assert.ok(all(dialog).some(e=>e.attrs["data-illustration"]==="water"));
 if(d.situation.number===17)assert.ok(all(dialog).some(e=>e.attrs['data-nationality']==='uk'));
 all(dialog).find(e=>e.textContent==="Launch situation game map").onclick();assert.equal(dialog.attrs["data-map-mode"],"game");assert.ok(all(dialog).some(e=>e.textContent===d.situation.title+" | Game map"));assert.ok(!all(dialog).some(e=>e.textContent==="Show source artwork"));
 if(d.situation.number===15){dialog.querySelector=selector=>all(dialog).find(e=>e.className===selector.slice(1));dialog.querySelector('.panzer-joined-scroll').scrollTop=240;all(dialog).find(e=>e.className==='panzer-token').onclick({stopPropagation(){}});assert.equal(dialog.querySelector('.panzer-joined-scroll').scrollTop,240);assert.ok(!all(dialog).some(e=>e.textContent==='Enlarge boards'));assert.equal(dialog.querySelector('.panzer-joined-scroll').scrollTop,240);}
 flow.returnParent();assert.equal(flow.active,false);assert.equal(JSON.parse(store.get("campaign-atlas:"+d.id+":v2")).gameLaunched,true);
}
flow.selectPackage(packages[0].id);assert.equal(flow.selectedPackage(),packages[0].id);assert.equal(store.size,16);
console.log("All imported cards: independent saves, campaign switching, source review, layouts and setup-to-game UI handlers passed. This is a DOM test double, not browser visual verification.");

const libraryUI=all(nodes.workflowChoose),chooser=libraryUI.find(e=>e.id==="legacyCampaignChoice");
chooser.value="ardennes-december-1944";libraryUI.find(e=>e.textContent==="Open campaign situations").onclick();
const parent=all(nodes.workflowInspector).find(e=>e.id==="campaignSituations");assert.equal(parent.hidden,false);assert.equal(nodes.workflowChoose.hidden,true);
assert.ok(all(parent).some(e=>e.textContent?.startsWith("01 ")&&e.textContent.includes("Bulge")));
assert.ok(all(parent).some(e=>e.textContent?.startsWith("02 ")&&e.textContent.includes("Bastogne")));
all(parent).find(e=>e.textContent==="Return to campaign selection").onclick();assert.equal(parent.hidden,true);
console.log("Library entry, campaign-local list and exit handlers passed.");

// Embedded campaign screen must use the campaign save callback, not standalone storage.
E.prototype.removeAttribute=function(k){delete this.attrs[k];};
const embeddedPackage=packages.find(d=>d.situation.number===14),embeddedPlan=model.create(embeddedPackage);
for(const side of embeddedPackage.setupOrder){fill(embeddedPlan,embeddedPackage,side);model.next(embeddedPlan,embeddedPackage);}
const center=new E('section'),cards=new E('aside');let campaignSave=null,exited=false;
const beforeStore=JSON.stringify([...store]);
ctx.window.CampaignSituationScreen.mount(embeddedPackage,{host:center,cards,plan:embeddedPlan,save:p=>campaignSave=p,exit:()=>exited=true});
assert.ok(all(cards).some(e=>e.textContent?.startsWith('Campaign Situation Card')));
flow.openMap();const embeddedDialog=center.children[0];assert.equal(embeddedDialog.attrs.open,'');
all(embeddedDialog).find(e=>e.textContent==='Launch situation game map').onclick();
assert.equal(embeddedDialog.attrs['data-map-mode'],'game');assert.equal(campaignSave.gameLaunched,true);assert.equal(JSON.stringify([...store]),beforeStore);
all(embeddedDialog).find(e=>e.textContent==='Review deployment').onclick();assert.equal(embeddedDialog.attrs['data-map-mode'],'setup');
ctx.window.CampaignSituationScreen.close();assert.equal(exited,true);
console.log('Embedded campaign card, original setup, game launch, deployment review and campaign-owned save callback passed.');
