const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto').webcrypto;
const M=require('./ardennes-command-state.js'),C=require('./campaign-world.js'),P=require('./ardennes-spatial.js');
let op=M.initial('guided-test','operational',10),n=0;const act=(type,data={})=>op=M.execute(op,{id:'c'+ ++n,revision:op.revision,type,...data});
act('allocate',{plan:{main:'M14',reserve:'M14',delivery:'M14'},sourceHashes:{M14:'fixture',M15:'fixture'}});while(op.time<50)act('advance');
let world=C.create(op,'0123456789abcdef0123456789abcdef',P),opened=[];
class E{constructor(tag,text){this.tag=tag;this.textContent=text;this.children=[];}append(...items){this.children.push(...items);this.lastChild=this.children.at(-1);}replaceChildren(){this.children=[];}setAttribute(){} }
const root=new E('div'),walk=e=>[e,...e.children.flatMap(walk)],sources=[14,15].map(n=>JSON.parse(fs.readFileSync(__dirname+'/sources/situations/panzer-leader-'+n+'.json','utf8')));
const ctx={console,crypto,TextEncoder,ArdennesCommand:M,CampaignWorld:C,document:{getElementById:()=>root,createElement:t=>new E(t),createTextNode:t=>new E('text',t)},localStorage:{getItem:()=>JSON.stringify(world)},window:{PANZER_SITUATION_LIBRARY:sources,CampaignRepository:{load:()=>world,get:()=>world,save:w=>world=w,saveOperation:s=>world={...world,operation:s}},ArdennesWorkspaceHandle:{update:()=>true,isLive:()=>true,renderSituation:()=>false},CampaignSituationIntegration:{open:id=>opened.push(id),continueToSetup:id=>opened.push('setup:'+id)}}};
(async()=>{await vm.runInNewContext(fs.readFileSync(__dirname+'/ardennes-command-view.js','utf8'),ctx);walk(root).find(e=>e.textContent==='Crossing defense (Bulge: Thrust) | Planned').onclick();walk(root).find(e=>e.textContent==='Commit defense plan').onclick();assert.deepEqual(opened,['M14']);assert.equal(world.operation.missions.M14.state,'Committed');const next=walk(root).find(e=>e.textContent==='Continue to Situation setup');assert.ok(next);next.onclick({preventDefault(){}});assert.deepEqual(opened,['M14','setup:M14']);assert.ok(walk(root).some(e=>e.textContent?.includes('Review the resulting Situation Card on the right')));console.log('Guided command/card transition passed: real commit opens card; left-pane continuation opens setup.');})().catch(e=>{console.error(e);process.exitCode=1;});
