const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const M=require('./ardennes-command-state.js');
const sources=Object.fromEntries([14,15].map(n=>['M'+n,JSON.parse(fs.readFileSync(__dirname+'/sources/situations/panzer-leader-'+n+'.json','utf8'))]));
let serial=0;const cmd=(s,type,data={})=>M.execute(s,{id:'c'+(++serial),revision:s.revision,type,...data});
const tick=(s,t)=>{while(s.time<t&&s.queue.length)s=cmd(s,'advance');return s;};
const start=(plan,test=false)=>cmd(M.initial('test','operational',10,test),'allocate',{plan,sourceHashes:{M14:'fixture14',M15:'fixture15'}});
for(const main of ['M14','M15']){let s=start({main,reserve:main,delivery:main});let p=M.preview(M.initial('x'),{main,reserve:main,delivery:main});assert.equal(p.rows.find(r=>r.id===main).reinforced,50);assert.equal(p.rows.find(r=>r.id!==main).supplied,100);assert.ok(M.ready(s,main,'reinforced'));s=tick(s,50);assert.equal(M.ready(s,main,'reinforced'),'');s=cmd(s,'commit',{mission:main,choice:'reinforced'});assert.equal(s.stock.F1,'consumed:'+main);assert.equal(s.reserve,'committed:'+main);assert.throws(()=>cmd(s,'commit',{mission:main,choice:'reinforced'}));const original=JSON.stringify(sources[main]),d=M.variant(s,main,sources[main]);assert.equal(d.totals.Allied,sources[main].totals.Allied+2);assert.equal(JSON.stringify(sources[main]),original);assert.deepEqual(M.restore(JSON.stringify(s)),s);}
let s=start({main:'M14',reserve:'M15',delivery:'guns'});s=tick(s,40);assert.equal(M.ready(s,'M14','supplied'),'');assert.equal(M.ready(s,'M15','supplied'),'');assert.ok(M.ready(s,'M15','reinforced'));s=tick(s,110);assert.equal(M.ready(s,'M15','reinforced'),'');
s=start({main:'M14',reserve:'retain',delivery:'guns'});assert.equal(s.trips.length,1);s=tick(s,40);assert.equal(s.stock.F1,'depot');s=cmd(s,'commit',{mission:'M14',choice:'baseline'});assert.equal(s.stock.A14,'M14');assert.equal(M.variant(s,'M14',sources.M14).totals.Allied,23);
assert.throws(()=>start({main:'M14',reserve:'M15',delivery:'M14'}));
s=start({main:'M14',reserve:'M14',delivery:'M14'},true);s=tick(s,10);s=cmd(s,'interrupt',{route:'M14'});assert.equal(s.stock.A14,'T1');assert.equal(s.trips[0].status,'held');assert.ok(!s.queue.some(e=>e.kind==='arrival'&&e.data.id==='T1'));s=cmd(s,'recall',{trip:'T1'});s=tick(s,40);assert.equal(s.stock.A14,'depot');assert.equal(s.stock.F1,'depot');
s=start({main:'M14',reserve:'M14',delivery:'M14'},true);s=tick(s,10);s=cmd(s,'interrupt',{route:'M14'});s=cmd(s,'reopen',{route:'M14'});s=tick(s,50);assert.equal(M.ready(s,'M14','reinforced'),'');s=cmd(s,'vacancy');assert.ok(M.ready(s,'M14','reinforced'));s=tick(s,60);assert.equal(M.ready(s,'M14','reinforced'),'');s=cmd(s,'commit',{mission:'M14',choice:'reinforced'});assert.throws(()=>cmd(s,'fixture',{mission:'M14',outcome:'held'}));s=cmd(s,'fixture-clock',{mission:'M14'});s=tick(s,120);s=cmd(s,'fixture',{mission:'M14',outcome:'lost'});assert.equal(s.missions.M14.state,'ReportPending');assert.equal(s.missions.M14.report,undefined);s=tick(s,125);assert.equal(s.missions.M14.report.reserveSurvivors,1);assert.throws(()=>cmd(s,'assess',{mission:'M14',action:'continue'}));s=cmd(s,'assess',{mission:'M14',action:'failure'});assert.equal(s.missions.M14.state,'Assessed');
const c={id:'duplicate',revision:s.revision,type:'advance'}; // no remaining event, failed command must not change input
const before=JSON.stringify(s);try{M.execute(s,c);}catch{}assert.equal(JSON.stringify(s),before);
let a=M.initial('essentials','essentials');a=cmd(a,'allocate',{plan:{main:'M15'}});assert.equal(a.plan.reserve,'M15');assert.equal(a.plan.delivery,'M15');const prior=a.commands[0];assert.deepEqual(M.execute(a,prior),a);assert.throws(()=>M.execute(a,{...prior,plan:{main:'M14'}}));assert.throws(()=>M.execute(a,{id:'stale',revision:0,type:'advance'}));assert.throws(()=>cmd(a,'fixture',{mission:'M15',outcome:'held'}));
// Exercise generated variants against the real deployment model, not a parallel mock.
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync(__dirname+'/panzer-situation-state.js','utf8'),ctx);const P=vm.runInContext('PanzerSituationModel',ctx);
for(const mission of ['M14','M15'])for(const choice of ['baseline','supplied','reinforced']){let x=start({main:mission,reserve:mission,delivery:mission});x=tick(x,50);x=cmd(x,'commit',{mission,choice});const d=M.variant(x,mission,sources[mission]),p=P.create(d);for(const side of d.setupOrder){for(const i of P.ground(d).filter(i=>d.counters.find(c=>c.id===i.counterTypeId).side===side)){const ref=d.deployment.allowedHexes[i.id][0],b=d.boards.find(b=>b.id===ref.boardId),h=b.hexes.find(h=>h.id===ref.hexId);P.place(p,d,i.id,b.id,h.imageCenter.u,h.imageCenter.v);}P.next(p,d);}P.validate(p,d);assert.equal(Object.keys(p.placements).length,d.instances.length);}
console.log('Ardennes command checks passed: delivery plans, readiness, conservation, variants, replay, source immutability, interruptions, recall, succession, delayed reports, duplicate/stale commands and real deployment integration.');
