const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');const ctx=vm.createContext({});for(const name of ['regional-state','situation-state','formation-state'])vm.runInContext(fs.readFileSync(__dirname+'/'+name+'.js','utf8'),ctx);
const R=vm.runInContext('RegionalModel',ctx),S=vm.runInContext('SituationModel',ctx),F=vm.runInContext('FormationModel',ctx),config=JSON.parse(fs.readFileSync(__dirname+'/regional-campaign.json','utf8'));
const state=R.create(config,'a','geo');state.missions.find(m=>m.id==='1-18-approaches').status='planned';const s=S.create(state,'1-18-approaches',config.cells[0],config);
const f=F.create(s);assert.equal(JSON.stringify(f),JSON.stringify(F.create(s)));assert.notEqual(JSON.stringify(f.cells),JSON.stringify(F.create({...s,campaignSeed:'b'}).cells));assert.equal(f.cells.length,99);F.validate(f,s);
const unit=f.counters[0],from=f.cells.find(c=>c.id===unit.cellId),target=f.cells.find(c=>F.distance(from,c)===1&&!f.counters.some(u=>u.cellId===c.id));assert.throws(()=>F.move(f,unit.id,target.id));F.next(f);F.next(f);F.move(f,unit.id,target.id);assert.ok(unit.spent>0);
unit.spent=4;assert.throws(()=>F.move(f,unit.id,from.id));for(let i=0;i<6;i++)F.next(f);assert.equal(f.side,'german');assert.equal(f.phase,0);assert.equal(unit.spent,0);assert.throws(()=>F.move(f,unit.id,from.id));for(let i=0;i<8;i++)F.next(f);assert.equal(f.turn,2);assert.equal(f.side,'american');F.validate(f,s);
const bad=JSON.parse(JSON.stringify(f));bad.counters[0].assetIds=['unknown'];assert.throws(()=>F.validate(bad,s));
const contact=F.create(s);contact.phase=2;const moving=contact.counters[0],origin=contact.cells.find(c=>c.id===moving.cellId),destination=contact.cells.find(c=>c.q===origin.q+1&&c.r===origin.r),enemyCell=contact.cells.find(c=>c.q===origin.q+2&&c.r===origin.r);contact.counters.push({id:'enemy',side:'german',cellId:enemyCell.id});F.move(contact,moving.id,destination.id);assert.equal(contact.contacts.length,1);assert.throws(()=>F.next(contact));assert.throws(()=>F.move(contact,moving.id,origin.id));
console.log('Formation checks passed: deterministic map, counter identity, phase and movement limits, side/turn transitions and contact pause.');
