<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LimboDancer.Domains.Asl.Units\LimboDancer.Domains.Asl.Units.csproj" />
    <ProjectReference Include="..\LimboDancer.Domains.Asl.Maps.Rendering\LimboDancer.Domains.Asl.Maps.Rendering.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\units\styles\*.uss" LogicalName="Styles.%(Filename)%(Extension)" Link="Styles\%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\units\palettes\*.palette.json" LogicalName="Palettes.%(Filename)%(Extension)" Link="Palettes\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
